name: Zara Stock Checker

on:
  schedule:
    # Her 30 dakikada bir çalışır (Saat başı ve buçuklarda)
    - cron: "0,30 * * * *"
  workflow_dispatch: # Manuel tetikleme butonu ekler

jobs:
  check-stock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          # SeleniumBase için gerekli driverları indirir
          sbase install chromedriver

      - name: Run Script
        env:
          # GitHub Secrets'tan değişkenleri alıp script'e verir
          WISHLIST_URL: ${{ secrets.WISHLIST_URL }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        # Xvfb sanal ekranını kullanarak headless modun düzgün çalışmasını sağlar
        run: |
          xvfb-run python script.py
